title: Tahanima Chowdhury
description: Software Engineer, QA @ Therap (BD) Ltd.
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "saifulcs40@gmail.com"
linkedin: "http://linkedin.com/in/saifcs40"
github: "https://github.com/saifulcs"
website: "#"
medium: "#"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
